name: Version and Publish

on:
  push:
    branches: [main]

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 50

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Cache PNPM store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install

      - name: Inject metadata into changeset files
        run: pnpm exec tsx scripts/inject-changeset-metadata.ts
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Version (bumps versions, updates changelogs, deletes .changeset/*.md)
        run: pnpm exec changeset version

      - name: Commit (version bump and changelog updates)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: version packages and update changelogs" || echo "No changes to commit"
          git push origin main

      - name: Publish to npm
        run: pnpm exec changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
